---
repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  # Disabling the separate yamllint as it can now be done by ansible-lint with our config moved to TLD.
  # - repo: 'https://github.com/adrienverge/yamllint.git'
  #   rev: v1.26.3
  #   hooks:
  #     - id: yamllint
  #       entry: yamllint -c .github/workflow-config/.yamllint.yml
  #       types:
  #         - yaml
  - repo: 'https://github.com/ansible-community/ansible-lint.git'
    rev: v6.14.3
    hooks:
      # see discussions here about what arguments are used, and behavior
      # https://github.com/ansible/ansible-lint/issues/649
      # Roles will trigger an "unknown file type"
      # https://github.com/ansible/ansible-lint/issues/808
      - id: ansible-lint
        pass_filenames: false
        always_run: true
        entry: "ansible-lint"
        args:
          - "--profile=production"
        additional_dependencies:
          - "ansible-core>=2.13"
          - "yamllint>=1.26,<2.0"
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.6.0
    hooks:
      - id: markdownlint-cli2
  # - repo: https://github.com/ambv/black
  #   rev: 23.3.0
  #   hooks:
  #     - id: black
  #       name: black
  #       entry: black
  #       args: [--config=.black.cfg, --check, --diff]
  #       types: [python]
  # - repo: https://github.com/pycqa/flake8
  #   rev: 6.0.0
  #   hooks:
  #     - id: flake8
  #       name: flake8
  #       entry: flake8
  #       types: [python]
...
