---
# tasks file for rh-console-imagebuilder
- name: Get access token
  ansible.builtin.uri:
    method: POST
    body:
      grant_type: refresh_token
      client_id: rhsm-api
      refresh_token: "{{ rhsm_offline_token | default(lookup('env', 'REDHAT_API_OFFLINE_TOKEN')) }}"
    body_format: form-urlencoded
    url: https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
  register: access_token_request

- name: Set fact for access token
  ansible.builtin.set_fact:
    rhsm_access_token: "{{ access_token_request.json.access_token }}"

- name: Start build process
  ansible.builtin.uri:
    method: POST
    body:
      distribution: "{{ imagebuilder_distribution }}"
      image_name: "{{ imagebuilder_image_name }}"
      image_requests:
        - architecture: "{{ imagebuilder_architecture }}"
          image_type: "{{ imagebuilder_image_type }}"
          upload_request:
            type: aws.s3
            options: {}
      customizations:
        packages: "{{ imagebuilder_image_packages }}"
        filesystem: "{{ imagebuilder_custom_filesystem }}"
    body_format: json
    url: https://console.redhat.com/api/image-builder/v1/compose
    headers:
      Authorization: "Bearer {{ rhsm_access_token }}"
    status_code: 201
  register: imagebuilder_compose_response

- name: Set fact for image id
  ansible.builtin.set_fact:
    imagebuilder_compose_id: "{{ imagebuilder_compose_response.json.id }}"

- name: Check build progress
  ansible.builtin.uri:
    headers:
      Authorization: "Bearer {{ rhsm_access_token }}"
    url: "https://console.redhat.com/api/image-builder/v1/composes/{{ imagebuilder_compose_id }}"
  register: imagebuilder_compose_status
  until: imagebuilder_compose_status.json.image_status.status == "success"
  retries: 10
  delay: 30

- name: Download image
  ansible.builtin.get_url:
    url: "{{ imagebuilder_compose_status.json.image_status.upload_status.options.url }}"
    dest: "{{ imagebuilder_dest_folder }}/{{ imagebuilder_image_name }}.vmdk"
    mode: '0644'
  when: imagebuilder_download_file is true

- name: Register stats for workflows
  ansible.builtin.set_stats:
    data:
    imagebuilder_download_url: "{{ imagebuilder_compose_status.json.image_status.upload_status.options.url }}"
...
