---
# aws
- name: "Setup upload request: AWS"
  when: imagebuilder_image_type == "aws"
  ansible.builtin.set_fact:
    imagebuilder_upload_request:
      type: "aws"
      options:
        share_with_accounts:
          "{{ imagebuilder_aws_account_number }}"

# gcp
- name: "Setup upload request: GCP"
  when: imagebuilder_image_type == "gcp" and
        imagebuilder_gcp_user is defined
  ansible.builtin.set_fact:
    imagebuilder_upload_request:
      type: "gcp"
      options:
        share_with_accounts:
          user: "{{ imagebuilder_gcp_user }}"

- name: "Setup upload request: GCP"
  when: imagebuilder_image_type == "gcp" and
        imagebuilder_gcp_service_account is defined
  ansible.builtin.set_fact:
    imagebuilder_upload_request:
      type: "gcp"
      options:
        share_with_accounts:
          serviceAccount: "{{ imagebuilder_gcp_service_account }}"

- name: "Setup upload request: GCP"
  when: imagebuilder_image_type == "gcp" and
        imagebuilder_gcp_group is defined
  ansible.builtin.set_fact:
    imagebuilder_upload_request:
      type: "gcp"
      options:
        share_with_accounts:
          group: "{{ imagebuilder_gcp_group }}"

- name: "Setup upload request: GCP"
  when: imagebuilder_image_type == "gcp" and
        imagebuilder_gcp_domain is defined
  ansible.builtin.set_fact:
    imagebuilder_upload_request:
      type: "gcp"
      options:
        share_with_accounts:
          domain: "{{ imagebuilder_gcp_domain }}"

# azure
- name: "Setup upload request: Azure"
  when: imagebuilder_image_type == "azure"
  ansible.builtin.set_fact:
    imagebuilder_upload_request:
      type: "azure"
      options:
        share_with_accounts:
          image_name: "{{ imagebuilder_image_name }}"
          resource_group: "{{ imagebuilder_azure_resource_group }}"
          subscription_id: "{{ imagebuilder_azure_subscription_id }}"
          tenant_id: "{{ imagebuilder_azure_tenant_id }}"

# default
- name: "Setup upload request: default"
  when: imagebuilder_upload_request is not defined
  ansible.builtin.set_fact:
    imagebuilder_upload_request:
      type: aws.s3
      options: {}
...
